export const INDIVIDUAL_PATROL_PLAN = 'INDIVIDUAL_PATROL_PLAN';

export const GROUP_PATROL_PLAN = 'GROUP_PATROL_PLAN';

export const ADD_DEVICES_ACTION = 'ADD_DEVICES';

export const REMOVE_DEVICES_ACTION = 'REMOVE_DEVICES';
