services:
  backend:
    image: harmless138/dojohub:0.1.0-askaripatrol
    restart: always
    ports:
      - ${LISTEN_PORT:?error}:${LISTEN_PORT:?error}
    env_file: .env
    environment:
      - DB_HOST=db

    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: package.json
  db:
    image: postgres:16.3-bookworm
    shm_size: 128mb
    ports:
      - ${DB_PORT:-5432}:5432
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME:?error}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?error}
      - POSTGRES_DB=${DB_NAME:?error}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USERNAME:?error} -d ${DB_NAME:?error}',
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
volumes:
  db-data:
