export const DELAYED_PATROL_CALL_QUEUE = 'DELAYED_PATROL_CALL_QUEUE';
export const DELAYED_PATROL_SMS_QUEUE = 'DELAYED_PATROL_SMS_QUEUE';

export const DELAYED_PATROL_CALL_QUEUE_TASK = 'DELAYED_PATROL_CALL_QUEUE_TASK';
export const DELAYED_PATROL_SMS_QUEUE_TASK = 'DELAYED_PATROL_SMS_QUEUE_TASK';
