export enum Action {
  CREATE = 'CREATE_ACTION',
  READ = 'READ_ACTION',
  UPDATE = 'UPDATE_ACTION',
  DELETE = 'DELETE_ACTION',
}

export enum Resource {
  SUPER_ADMIN = 'SUPER_ADMIN_RESOURCE',
  COMPANY = 'COMPANY_RESOURCE',
  COMPANY_ADMIN = 'COMPANY_ADMIN_RESOURCE',
  SITE_ADMIN = 'SITE_ADMIN_RESOURCE',
  SECURITY_GUARD = 'SECURITY_GUARD_RESOURCE',
  SITE = 'SITE_RESOURCE',
  TAG = 'TAG_RESOURCE',
  SHIFT = 'SHIFT_RESOURCE',
  PATROL = 'PATROL_RESOURCE',
  NOTIFICATION = 'NOTIFICATION_RESOURCE',
  STATS = 'STATISTICS',
}
