export const COMPANY_RESOURCE = '16';

export const DEVICE_RESOURCE = '32';

export const SITE_RESOURCE = '64';

export const SHIFT_RESOURCE = '128';

export const PATROL_RESOURCE = 'PATROL_RESOURCE';

export const SUPER_ADMIN_RESOURCE = 'SUPER_ADMIN_RESOURCE';

export const COMPANY_ADMIN_RESOURCE = 'COMPANY_ADMIN_RESOURCE';

export const SITE_ADMIN_RESOURCE = 'SITE_ADMIN_RESOURCE';

export const SECURITY_GUARD_RESOURCE = 'SECURITY_GUARD_RESOURCE';
